### ISSUE TITLE
Crash on initialize

### ISSUE THREAD

**Issue by mon** [mheese/rust-pkcs11#2]
This is my first Rust program! Be gentle.

```rust
extern crate pkcs11;

fn main() {
    let mut ctx = pkcs11::Ctx::new("eToken").unwrap();
    ctx.initialize(None).expect("Couldn't initialize dongle libary");
}
```
Crashes with an invalid memory read.
Drivers from [here](https://support.globalsign.com/customer/portal/articles/1698654-safenet-drivers) - I'm using 10.3. Thankfully you don't need a dongle attached, simply loading the library is enough to break things.

**Comment by mon** [comment]
I just downloaded the master repo and used that - it's working.
Could you update the crate?

**Comment by mon** [comment]
I hope you're not tired of notifications yet.

My PKCS11 library is strict-  the struct returned from C_GetFunctionsList is packed. With `#[repr(packed)]`, the library loads and functions as expected. However, this throws a bunch of deprecation warnings and will have to be worked around later.

Shall I make a pull, or do you have anything else in mind?

**Comment by mheese** [comment]
@mon Very sorry, I just saw this issue and your comments.

sure! Please *do* make a PR for what works for you! Keep in mind that I have been strictly testing this with SoftHSM so far (as it is very easy to program against it).

You said your library does not have `C_WaitForSlotEvent`. Which PKCS11 version is the library? I haven't really thought about the different library versions and what implications they have for loading the library.

**Comment by mon** [comment]
I've actually found a few more showstopping issues since. They add up to a very frustrating experience.

`C_WaitForSlotEvent` is the only "extra" function I can see that was added later in the spec (2.01 apparently). My library says it's 2.01, so clearly it lies.

All the structs have to be packed, which works now but Debug/Copy traits won't be supported in later releases of rustc. This makes me wary to implement `#[repr(packed)]` on everything. The only solution I can think of is a "shadow" struct with packed attributes that is then copied attr by attr to a sane rust-style struct with the same members. It makes the code awkward, but it should work.

Now for the final big one...
`CK_ULONG` is `unsigned long int`. On Windows x64, this ends up being 32 bits. So you'd need 1) a cfg switch to set `CK_ULONG` to a `u32` on windows and `usize` on linux, but 2) all the `ulValueLen` members of attribute structs (etc...) are given something from `std::mem::size_of`, which would need to be truncated every time.

The whole thing feels very messy, with dual-structs and down-casting size values. As I'm new to rust - is there an easier way?

**Comment by mheese** [comment]
@mon I wouldn't proclaim myself to be an expert in rust either, however, your changes definitely makes sense. With regards to CK_ULONG, I'm pretty sure somebody in the rust community / on the rust channels is going to be able to help us out on this. For now I just merged it and I will see if this is going to cause issues for me now :)

**Comment by mon** [comment]
Alright, sounds great! Thanks for the merge.

**Comment by mon** [comment]
Only realised this now - could you push these as a new crate version? Thanks!
