### ISSUE TITLE
Commit "Fix Windows x64 compatiblity" breaks MacOS

### ISSUE THREAD

**Issue by bpressure** [mheese/rust-pkcs11#4]
Hi,

on MacOS I do get a "(signal: 11, SIGSEGV: invalid memory reference)" Segmentation fault when i call ```ctx.initialize(None)```
Commit 74057c9edd93db382d7552ad9c1077159654d40c works fine, so it has to be the "Fix Windows x64 compatiblity" commit.

Any idea why?

**Comment by bpressure** [comment]
I run it with SoftHSM v2.4.0, compiled with rustc 1.26.0-nightly on MacOS 10.13.3

**Comment by pat2man** [comment]
I am seeing the same problem. Reverting to the previous commit fixes it.

**Comment by srinivasanraghavan** [comment]
I also get the same error but i custom a PKCS11 implementation . But i switch back to prev version its working

**Comment by mheese** [comment]
@mon interesting ... can you point me to that part of the documentation?

**Comment by mon** [comment]
@mheese from pkcs11.h:

```c
 * In addition to defining these 5 macros, the packing convention
 * for Cryptoki structures should be set.  The Cryptoki
 * convention on packing is that structures should be 1-byte
 * aligned.

.... windows instructions follow, then

 * In a UNIX environment, you're on your own for this.  You might
 * not need to do (or be able to do!) anything.

```
