### ISSUE TITLE
CK_ATTRIBUTE get_biginteger mixes up endianness

### ISSUE THREAD

**Issue by nickray** [mheese/rust-pkcs11#44]
Cryptoki base spec defines "Big integer (...) a string of `CK_BYTE`s representing an unsigned integer of arbitrary size, most-significant byte first (e.g., the integer 32768 is represented as the 2-byte string 0x80 0x00)".

Meanwhile, this library parses as little endian: https://github.com/mheese/rust-pkcs11/blob/1323d5f4cc4774235ef327d0f819804e2b6f2894/src/types.rs#L853-L858

**Comment by mrodden** [comment]
Yeah I just hit this too... was super confused that the lib assumes LE... which is totally not what all my other sources say including the spec.

**Comment by nickray** [comment]
It's just a typo, ASN1 is definitely BE.

**Comment by mheese** [comment]
yeah, good find guys! 👍

**Comment by mheese** [comment]
Please switch to the cryptoki crate: https://github.com/parallaxsecond/rust-cryptoki
