### ISSUE TITLE
possible segmentation fault

### ISSUE THREAD

**Issue by charlesxsh** [mheese/rust-pkcs11#54]
Hi there, due to public new function available for type, there is an potential segmentation fault chance without any unsafe involved.

```
fn main() {
    let a = pkcs11::types::CK_ATTRIBUTE::new(123);
    a.get_bool(); // get_bool can also be replaced with any member functions contains dereference operation without check pointer is null 
}
```

```bash
cargo run
```

```
Segmentation fault
```

**Comment by mheese** [comment]
@charlesxsh please switch to using the cryptoki crate https://github.com/parallaxsecond/rust-cryptoki . I'm no longer maintaining this reop.
