### ISSUE TITLE
Report as unmaintained?

### ISSUE THREAD

**Issue by ionut-arm** [mheese/rust-pkcs11#57]
Hey!

I wanted to check whether you're confortable with us marking `pkcs11` as unmaintained in the Rustsec [advisory database](https://github.com/rustsec/advisory-db)?

**Comment by mheese** [comment]
@ionut-arm yes, please ... and I can see you did that already :) ... also glad to see that there is a replacement/fork which is fixing all the things which I wanted to as well.
