### ISSUE TITLE
latest code not available in https://crates.io/

### ISSUE THREAD

**Issue by srinivasanraghavan** [mheese/rust-pkcs11#6]
Can you help with the latest code in https://crates.io/

**Comment by mon** [comment]
*bump* with the new features added, could this be pushed?

**Comment by mheese** [comment]
@mon @srinivasanraghavan can someone of you please test if 0.3.0 suits your needs? We can close this issue then.

**Comment by mon** [comment]
@mheese windows x64 strikes again

```
: mismatched types
   --> pkcs11-0.3.0\src\lib.rs:890:64
    |
890 |         match (self.C_Sign)(session, data.as_slice().as_ptr(), data.len(), signature.as_slice().as_ptr(), &signatureLen) {
    |                                                                ^^^^^^^^^^ expected u32, found usize
```

just add back the `data.len() as CK_ULONG` and it should be good to go

**Comment by mheese** [comment]
there was  a merge conflict ... I thought I got it right :)

**Comment by mheese** [comment]
@mon released version 0.3.1 which addresses that

**Comment by mon** [comment]
All good now, cheers! My cargo.toml is pretty again :D

**Comment by mheese** [comment]
Thanks again @mon ! And sorry about the huge delay.
