### ISSUE TITLE
Ctx::new should take a &Path

### ISSUE THREAD

**Issue by mathstuf** [mheese/rust-pkcs11#9]
It's treated as a path, so it'd be nice to have the type reflect that.

**Comment by mathstuf** [comment]
Or `AsRef<Path>`.

**Comment by mathstuf** [comment]
Ah. It also shouldn't be a `'static` lifetime.

**Comment by mheese** [comment]
hm, I vaguely remember that there was a reason why it is as it is right now. However, looking at it again right now, I don't recall :)

I'll look into it because the request totally makes sense :+1: Thanks for reporting
